import { Router } from 'express';
import { adminController } from '../controllers/admin.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/dashboard', adminController.getDashboardStats);
router.get('/users', adminController.getAllUsers);
router.post('/users', adminController.createUser);
router.put('/users/:id', adminController.updateUser);
router.put('/users/:id/toggle', adminController.toggleUserStatus);
router.put('/users/:id/reset-password', adminController.resetUserPassword);
router.post('/users/:id/impersonate', adminController.impersonateUser);
router.delete('/users/:id', adminController.deleteUser);
router.get('/settings', adminController.getSettings);
router.put('/settings/:key', adminController.updateSetting);
router.get('/modules', adminController.getModules);
router.put('/modules/:id/toggle', adminController.toggleModule);
router.get('/plans', adminController.getPlans);
router.get('/audit-log', adminController.getAuditLog);
router.get('/health', adminController.getSystemHealth);
router.get('/system-stats', adminController.getSystemStats);
router.get('/db-stats', adminController.getDBStats);
router.get('/user-activity', adminController.getUserActivity);
router.get('/tenants', adminController.getTenants);
router.post('/broadcast', adminController.broadcastNotification);
router.post('/cleanup', adminController.runCleanup);
export default router;