import { Router } from 'express';
import { adminController } from '../controllers/admin.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/dashboard', adminController.getDashboardStats);
router.get('/users', adminController.getAllUsers);
router.put('/users/:id/toggle', adminController.toggleUserStatus);
router.put('/users/:id/reset-password', adminController.resetUserPassword);
router.delete('/users/:id', adminController.deleteUser);
router.get('/settings', adminController.getSettings);
router.put('/settings/:key', adminController.updateSetting);
router.get('/modules', adminController.getModules);
router.put('/modules/:id/toggle', adminController.toggleModule);
router.get('/plans', adminController.getPlans);
router.get('/audit-log', adminController.getAuditLog);
router.get('/health', adminController.getSystemHealth);
router.get('/tenants', adminController.getTenants);
export default router;