import { Router } from 'express';
import { analyticsController } from '../controllers/analytics.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/customers', analyticsController.getCustomerAnalytics);
router.get('/orders', analyticsController.getOrderAnalytics);
router.get('/tiers', analyticsController.getTiers);
router.get('/tier/:email', analyticsController.getCustomerTier);
router.get('/campaigns', analyticsController.getCampaigns);
router.post('/campaigns', analyticsController.createCampaign);
router.post('/track-visit', analyticsController.trackVisit);
export default router;