import { Router } from 'express';
import { budgetController } from '../controllers/budget.controller';
import { authenticate } from '../middleware/auth';
import { authorize } from '../middleware/authorize';
const router = Router();
router.use(authenticate);
router.get('/', authorize('budget:read'), budgetController.getAll);
router.get('/stats', authorize('budget:read'), budgetController.getStats);
router.get('/transactions', authorize('budget:read'), budgetController.getTransactions);
router.post('/', authorize('budget:create'), budgetController.create);
router.put('/:id', authorize('budget:update'), budgetController.update);
router.delete('/:id', authorize('budget:delete'), budgetController.delete);
export default router;
