import { Router } from 'express';
import { orderController } from '../controllers/order.controller';
import { authenticate } from '../middleware/auth';
import { authorize } from '../middleware/authorize';
const router = Router();
router.use(authenticate);
router.get('/', authorize('orders:read'), orderController.getAll);
router.get('/stats', authorize('orders:read'), orderController.getStats);
router.get('/:id', authorize('orders:read'), orderController.getById);
router.post('/', authorize('orders:create'), orderController.create);
router.put('/:id/status', authorize('orders:update'), orderController.updateStatus);
router.delete('/:id', authorize('orders:delete'), orderController.delete);
export default router;
