import { Router } from 'express';
import { travelController as ctrl } from '../controllers/travel.controller';
import { authenticate } from '../middleware/auth';
const router = Router();
router.use(authenticate);
router.get('/', ctrl.getAll);
router.post('/', ctrl.create);
router.put('/:id/status', ctrl.updateStatus);
router.get('/stats', ctrl.getStats);
export default router;